[package]
name = "elevator"
version = "0.1.0"
authors = ["Pollapee <im.oab.ps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.5.8"
lazy_static = "1.4.0"
rand = "0.7"